/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.badgeforce_pb.Account', null, global);
goog.exportSymbol('proto.badgeforce_pb.Account.EntityType', null, global);
goog.exportSymbol('proto.badgeforce_pb.Account.PublicData', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.badgeforce_pb.Account = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.badgeforce_pb.Account, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.badgeforce_pb.Account.displayName = 'proto.badgeforce_pb.Account';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.badgeforce_pb.Account.prototype.toObject = function(opt_includeInstance) {
  return proto.badgeforce_pb.Account.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.badgeforce_pb.Account} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.badgeforce_pb.Account.toObject = function(includeInstance, msg) {
  var f, obj = {
    publickey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    publicdata: (f = msg.getPublicdata()) && proto.badgeforce_pb.Account.PublicData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.badgeforce_pb.Account}
 */
proto.badgeforce_pb.Account.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.badgeforce_pb.Account;
  return proto.badgeforce_pb.Account.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.badgeforce_pb.Account} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.badgeforce_pb.Account}
 */
proto.badgeforce_pb.Account.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublickey(value);
      break;
    case 2:
      var value = new proto.badgeforce_pb.Account.PublicData;
      reader.readMessage(value,proto.badgeforce_pb.Account.PublicData.deserializeBinaryFromReader);
      msg.setPublicdata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.badgeforce_pb.Account.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.badgeforce_pb.Account.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.badgeforce_pb.Account} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.badgeforce_pb.Account.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPublickey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPublicdata();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.badgeforce_pb.Account.PublicData.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.badgeforce_pb.Account.EntityType = {
  PERSON: 0,
  ORGANIZATION: 1
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.badgeforce_pb.Account.PublicData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.badgeforce_pb.Account.PublicData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.badgeforce_pb.Account.PublicData.displayName = 'proto.badgeforce_pb.Account.PublicData';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.badgeforce_pb.Account.PublicData.prototype.toObject = function(opt_includeInstance) {
  return proto.badgeforce_pb.Account.PublicData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.badgeforce_pb.Account.PublicData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.badgeforce_pb.Account.PublicData.toObject = function(includeInstance, msg) {
  var f, obj = {
    number: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dateofbirth: jspb.Message.getFieldWithDefault(msg, 2, ""),
    address: jspb.Message.getFieldWithDefault(msg, 3, ""),
    photo: jspb.Message.getFieldWithDefault(msg, 4, ""),
    url: jspb.Message.getFieldWithDefault(msg, 5, ""),
    name: jspb.Message.getFieldWithDefault(msg, 6, ""),
    type: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.badgeforce_pb.Account.PublicData}
 */
proto.badgeforce_pb.Account.PublicData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.badgeforce_pb.Account.PublicData;
  return proto.badgeforce_pb.Account.PublicData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.badgeforce_pb.Account.PublicData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.badgeforce_pb.Account.PublicData}
 */
proto.badgeforce_pb.Account.PublicData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNumber(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDateofbirth(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoto(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 7:
      var value = /** @type {!proto.badgeforce_pb.Account.EntityType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.badgeforce_pb.Account.PublicData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.badgeforce_pb.Account.PublicData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.badgeforce_pb.Account.PublicData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.badgeforce_pb.Account.PublicData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumber();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDateofbirth();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPhoto();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional string number = 1;
 * @return {string}
 */
proto.badgeforce_pb.Account.PublicData.prototype.getNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Account.PublicData.prototype.setNumber = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string dateOfBirth = 2;
 * @return {string}
 */
proto.badgeforce_pb.Account.PublicData.prototype.getDateofbirth = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Account.PublicData.prototype.setDateofbirth = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string address = 3;
 * @return {string}
 */
proto.badgeforce_pb.Account.PublicData.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Account.PublicData.prototype.setAddress = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string photo = 4;
 * @return {string}
 */
proto.badgeforce_pb.Account.PublicData.prototype.getPhoto = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Account.PublicData.prototype.setPhoto = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string url = 5;
 * @return {string}
 */
proto.badgeforce_pb.Account.PublicData.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Account.PublicData.prototype.setUrl = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string name = 6;
 * @return {string}
 */
proto.badgeforce_pb.Account.PublicData.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Account.PublicData.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional EntityType type = 7;
 * @return {!proto.badgeforce_pb.Account.EntityType}
 */
proto.badgeforce_pb.Account.PublicData.prototype.getType = function() {
  return /** @type {!proto.badgeforce_pb.Account.EntityType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {!proto.badgeforce_pb.Account.EntityType} value */
proto.badgeforce_pb.Account.PublicData.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional string publicKey = 1;
 * @return {string}
 */
proto.badgeforce_pb.Account.prototype.getPublickey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Account.prototype.setPublickey = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional PublicData publicData = 2;
 * @return {?proto.badgeforce_pb.Account.PublicData}
 */
proto.badgeforce_pb.Account.prototype.getPublicdata = function() {
  return /** @type{?proto.badgeforce_pb.Account.PublicData} */ (
    jspb.Message.getWrapperField(this, proto.badgeforce_pb.Account.PublicData, 2));
};


/** @param {?proto.badgeforce_pb.Account.PublicData|undefined} value */
proto.badgeforce_pb.Account.prototype.setPublicdata = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.badgeforce_pb.Account.prototype.clearPublicdata = function() {
  this.setPublicdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.badgeforce_pb.Account.prototype.hasPublicdata = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.badgeforce_pb);
